version: '3.8' # no es la versi칩n de docker-compose, sino la versi칩n de la sintaxis del archivo
x-defaults-container: &container-defaults
  restart: unless-stopped
  stop_grace_period: 3s
services:
  api:
    build:
      context: ./API
      dockerfile: development.Dockerfile
      args:
        API_PORT: 3000
        NODE_VERSION: 21-alpine
    container_name: api
    env_file:
      - .env
    volumes:
      - ./API:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - db
    <<: *container-defaults

  rails:
    build:
      context: ./SENDER/wellproject
    container_name: rails_2
    env_file:
      - .env
    volumes:  
      - ./SENDER/wellproject:/rails
      - bundle-data_2:/usr/local/bundle
    ports:  
      - 3001:3000
    depends_on: []
    environment:
      RAILS_ENV: development
    <<: *container-defaults

  db:
    image: postgres:14.11-alpine3.19  # Usa la imagen m치s reciente de PostgreSQL
    environment:
      POSTGRES_DB: ${DB_NAME}   # Nombre de la base de datos
      POSTGRES_USER: ${DB_USERNAME}     # Usuario de la base de datos
      POSTGRES_PASSWORD: ${DB_PASSWORD}  # Contrase침a del usuario
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persiste los datos entre reinicios del contenedor
    ports:
      - "5433:5432"  # Mapea el puerto 5432 del contenedor al mismo puerto en el host
    <<: *container-defaults
volumes:
  postgres_data:   # Define el volumen para almacenar datos
  bundle-data_2: # para almacenar las gemas de rails
